CREATE TABLE public.pessoa
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cpf character varying(11) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    endereco character varying(150) COLLATE pg_catalog."default" NOT NULL,
    created_at date,
    updated_at date,
    CONSTRAINT pessoa_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE public.pessoa
    OWNER to postgres;
	
CREATE TABLE public.divida
(
    id integer NOT NULL,
    pessoa_id integer NOT NULL,
    created_at date NOT NULL,
    updated_at date NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT pessoa_id_fk FOREIGN KEY (pessoa_id)
        REFERENCES public.pessoa (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
);

ALTER TABLE public.divida
    OWNER to postgres;